version : '3.9'

services:
  web:
    build: ./myproject
    container_name: web
    ports:
      - "9000:9000"
    volumes:
      - app_logs:/app/logs
    env_file:
      - ./myproject/.env.web
    networks:
      - mynet
    depends_on:
      - db
      - web_nginx
  
  db:
    image: docker.io/library/postgres:15
    container_name: db
    restart: always
    ports:
      - "5435:5432"
    env_file:
      - ./myproject/.env.postgres
    networks:
      - mynet
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    image: nginx:latest
    container_name: web_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web 
    networks:
      - mynet
    
  
volumes:
  postgres_data:
  app_logs:
  
networks:
  mynet:
    driver: bridge