events {}
http {
    upstream django_app {
        server web:9000;   # internal service name + port
    }

    server {
        listen 80;

        location / {
            proxy_pass http://django_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
