FROM python:3.13.13

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

EXPOSE 9000

CMD ["python","manage.py","runserver","0.0.0.0:9000","--insecure"]